
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
