name: CI/CD — Build, Test & Push Dockerized App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔑 Login to DockerHub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push backend
      - name: Build & Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: mohxmd77/backend-app:latest

      # Build & Push frontend
      - name: Build & Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: mohxmd77/frontend-app:latest
